imports:
   - { resource: "services/repositories.yml" }
   - { resource: "services/events.yml" }
   - { resource: "services/authentication.yml" }
   - { resource: "services/transformers.yml" }

services:
    core.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder
    core.serializer.default:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            0:
                - '@serializer.normalizer.object'
            1:
                - '@core.encoder.json'
    core.doctrine.entity_listener_resolver:
        class: CoreBundle\Doctrine\EntityListenerResolver
        arguments: [ "@service_container" ]
    user.listener:
        class: CoreBundle\Entity\Listener\UserListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.orm.entity_listener }
    core.user_aware_service:
        class: CoreBundle\Service\UserAwareService
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage', '@event.notification_manager']
    user.service:
        class:  CoreBundle\Service\User
        parent: core.user_aware_service
        calls:
          - ['setPasswordEncoder', ['@security.password_encoder']]
    security.authentication.success_handler:
        class: CoreBundle\Service\Handler\AuthenticationSuccessHandler
        arguments: ['@security.http_utils', '@service_container', {}]
        tags:
            - { name: 'monolog.logger', channel: 'security'}