sudo: required

services:
  - docker

before_install:
  - cp .env.dist .env
  - cp app/config/{parameters.yml.dist,parameters.yml}
  - docker-compose up -d
  - docker-compose ps


script:
  - docker-compose run --rm php bash -c "make setup && make test"

#after_success:
#  - codecov
