services:
    event.event_dispatcher:
        class: CoreBundle\Event\EventDispatcher
        autowire: true
    event.notification_manager:
        class: CoreBundle\Event\NotificationManager
        arguments: ['@event.event_dispatcher']
    event.listener.votes:
        class: CoreBundle\Event\Listener\VoteListener
        arguments: ['@repository.vote_repository']
        tags:
            - {name: "kernel.event_listener", event: "vote.add", method: "onAddVoteEvent"}
            - {name: "kernel.event_listener", event: "vote.revoke", method: "onRevokeVoteEvent"}