CoreBundle\Entity\Instrument:
    type: entity
    table: instruments
    repositoryClass: CoreBundle\Repository\InstrumentRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
        photo:
            type: string
            nullable: true
            length: 255