api_security:
    type: rest
    prefix: 'auth'
    resource: "ApiBundle\\Controller\\SecurityController"
api_genres:
    type: rest
    resource: "ApiBundle\\Controller\\GenreController"
api_votes:
    type: rest
    resource: "ApiBundle\\Controller\\VoteController"